### ISSUE TITLE
Will you add new drivers?

### ISSUE THREAD

**Issue by AGR2017** [hmtheboy154/Darkmatter-kernel#1]
- Lenovo EasyCamera - Realtek
- Conexant microphone and sound driver

    Will you give the latest kernel download link?

**Comment by hmtheboy154** [comment]
Which device am I trying to support here ?
And latest kernel is in BlissOS btw

**Comment by AGR2017** [comment]
lenovo g50-80

**Comment by AGR2017** [comment]
> Which device am I trying to support here ? And latest kernel is in BlissOS btw

Lenovo g50-80E

**Comment by hmtheboy154** [comment]
G50-80 80E5 ?

**Comment by AGR2017** [comment]
> G50-80 80E5 ?

Yes

Bluetooth driver

Camera driver

Microphone driver

**Comment by hmtheboy154** [comment]
Not every G50-80 are the same, it's better if you paste the info of your laptop somewhere with full detail and send it here. 
Here are some of the detail that I've found :
The camera is just using uvc camera, it should work just fine. There are a lot of camera that the G50-80 shipped with : 
http://linux-hardware.org/?id=usb:0bda-579a
http://linux-hardware.org/?id=usb:13d3-5727
http://linux-hardware.org/?id=usb:0c45-6513

Same with Bluetooth, some are shipped with Intel card, some are shipped with Realtek one. If it's Intel then probably it will work fine on Bliss. 

For Audio, it should work too I guess, or else wait for the new BlissOS updates. It will include a new audio HAL from Project Celadon and I tested with a laptop that use Conexant audio (Thinkpad T420) and it works.

**Comment by hmtheboy154** [comment]
I recommend you test the hardware on a linux distro, and then get the hardware info on it too.

**Comment by AGR2017** [comment]
> Not every G50-80 are the same, it's better if you paste the info of your laptop somewhere with full detail and send it here. Here are some of the detail that I've found : The camera is just using uvc camera, it should work just fine. There are a lot of camera that the G50-80 shipped with : http://linux-hardware.org/?id=usb:0bda-579a http://linux-hardware.org/?id=usb:13d3-5727 http://linux-hardware.org/?id=usb:0c45-6513
> 
> Same with Bluetooth, some are shipped with Intel card, some are shipped with Realtek one. If it's Intel then probably it will work fine on Bliss.
> 
> For Audio, it should work too I guess, or else wait for the new BlissOS updates. It will include a new audio HAL from Project Celadon and I tested with a laptop that use Conexant audio (Thinkpad T420) and it works.

The audio working fine but microphone not working 
The Bluetooth not working efficient. Sometimes working but very slowly (low speed)
Android 9 Camera was working but android 12 not working
Laptop model - Lenovo G50-80E5
Serial Number - PF070EZY
https://pcsupport.lenovo.com/us/en/products/laptops-and-netbooks/lenovo-g-series-laptops/g50-80/80e5/80e501bsax/pf070ezy/downloads/driver-list

**Comment by hmtheboy154** [comment]
> > Not every G50-80 are the same, it's better if you paste the info of your laptop somewhere with full detail and send it here. Here are some of the detail that I've found : The camera is just using uvc camera, it should work just fine. There are a lot of camera that the G50-80 shipped with : http://linux-hardware.org/?id=usb:0bda-579a http://linux-hardware.org/?id=usb:13d3-5727 http://linux-hardware.org/?id=usb:0c45-6513
> > Same with Bluetooth, some are shipped with Intel card, some are shipped with Realtek one. If it's Intel then probably it will work fine on Bliss.
> > For Audio, it should work too I guess, or else wait for the new BlissOS updates. It will include a new audio HAL from Project Celadon and I tested with a laptop that use Conexant audio (Thinkpad T420) and it works.
> 
> The audio working fine but microphone not working The Bluetooth not working efficient. Sometimes working but very slowly (low speed) Android 9 Camera was working but android 12 not working Laptop model - Lenovo G50-80E5 Serial Number - PF070EZY https://pcsupport.lenovo.com/us/en/products/laptops-and-netbooks/lenovo-g-series-laptops/g50-80/80e5/80e501bsax/pf070ezy/downloads/driver-list

Which Android 12 ? BlissOS 15.8.6 ?

**Comment by AGR2017** [comment]
> > > Not every G50-80 are the same, it's better if you paste the info of your laptop somewhere with full detail and send it here. Here are some of the detail that I've found : The camera is just using uvc camera, it should work just fine. There are a lot of camera that the G50-80 shipped with : http://linux-hardware.org/?id=usb:0bda-579a http://linux-hardware.org/?id=usb:13d3-5727 http://linux-hardware.org/?id=usb:0c45-6513
> > > Same with Bluetooth, some are shipped with Intel card, some are shipped with Realtek one. If it's Intel then probably it will work fine on Bliss.
> > > For Audio, it should work too I guess, or else wait for the new BlissOS updates. It will include a new audio HAL from Project Celadon and I tested with a laptop that use Conexant audio (Thinkpad T420) and it works.
> > 
> > 
> > The audio working fine but microphone not working The Bluetooth not working efficient. Sometimes working but very slowly (low speed) Android 9 Camera was working but android 12 not working Laptop model - Lenovo G50-80E5 Serial Number - PF070EZY https://pcsupport.lenovo.com/us/en/products/laptops-and-netbooks/lenovo-g-series-laptops/g50-80/80e5/80e501bsax/pf070ezy/downloads/driver-list
> 
> Which Android 12 ? BlissOS 15.8.6 ?

Yes
